version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecs: circleci/aws-ecs@1.1.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: "cfb-guide-image-repo"
          region: AWS_DEFAULT_REGION
          tag: "build-${CIRCLE_BUILD_NUM},latest"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: AWS_DEFAULT_REGION
          family: "cfb-guide-graphql-family"
          service-name: "cfb-guide-graphql-service"
          cluster-name: "cfb-guide-graphql-cluster"
          container-image-name-updates: "container=cfb-guide-graphql"